# Generated by Django 4.0.4 on 2022-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerveza',
            name='envase',
            field=models.CharField(choices=[('lata', 'Lata'), ('botella', 'Botella')], default='botella', max_length=7),
        ),
    ]
