# Generated by Django 4.0.4 on 2022-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0002_cerveza_envase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerveza',
            old_name='descripcion',
            new_name='descripción',
        ),
        migrations.AddField(
            model_name='cerveza',
            name='grado_alcohol',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
